remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

title: Dhruv Bagda
description: AI Research Portfolio

header_pages:
  - index.md
  - projects.md
  - research.md
  - blog.md
  - about.md
